In [1]:
from copy import deepcopy
import numpy as np
import pandas as pd
import sys

In [50]:
#import dataset
myMap = {"Iris-setosa":0,"Iris-versicolor":1,"Iris-virginica":2}
filename = "/Users/ziyangliu/Documents/CS446/KMeansClustering/data/iris.data"
lines = [line.rstrip('\n').split(",") for line in open(filename,"r")] 
lines.pop(0)
data = np.array(lines)
X = data[:,0:4].astype(np.float)
Y = data[:,4]
N = Y.shape[0]
for i in range(N):
    Y[i] = myMap[Y[i]]
Y = Y.astype(np.float)

In [64]:
# Make 3  clusters
k = 3
# Initial Centroids
C = [[2.,  0.,  3.,  4.], [1.,  2.,  1.,  3.], [0., 2.,  1.,  0.]]
C = np.array(C)
print("Initial Centers")
print(C)

Initial Centers
[[ 2.  0.  3.  4.]
 [ 1.  2.  1.  3.]
 [ 0.  2.  1.  0.]]


In [179]:
def choose(x,C_curr):
    dist = np.square(C_curr-x)
    dist = np.sum(dist,axis = 1)
    return np.argmin(dist)

def k_means(C):
    '''
    Repeat until convergence:
        2.1 (Recenter.) Set μj := mean(Cj) for j ∈ (1,...,k).
        2.2 (Reassign). Update Cj := {xi : μ(xi) = μj} for j ∈ (1,...,k)
        (break ties arbitrarily).
    '''
    pred = np.zeros(N)
    K = C.shape[0]
    D = C.shape[1]
    C_next = np.zeros((K,D))
    C_curr = C
    for i in range(N):
        pred[i] = choose(X[i],C_curr)
    for k in range(K):
        C_next[k] = np.mean(X[pred==k],axis = 0)
    while not np.array_equal(C_next,C_curr):
        C_curr = deepcopy(C_next)
        for i in range(N):
            pred[i] = choose(X[i],C_curr)
        for k in range(K):
            C_next[k] = np.mean(X[pred==k],axis = 0)            
    return C_next
        
    
        

In [180]:
k_means(C)

ok
ok
ok
ok
ok


array([[ 6.30103093,  2.88659794,  4.95876289,  1.69587629],
       [ 5.21612903,  3.53870968,  1.68064516,  0.35806452],
       [ 4.70909091,  3.10909091,  1.39545455,  0.19090909]])

In [168]:
c1 = np.sum(X[0:50,:],axis = 0)
c2 = np.sum(X[50:100,:],axis = 0)
c3 = np.sum(X[100:150,:],axis = 0)
print(c1/50)
print(c2/50)
print(c3/50)

[ 5.006  3.418  1.464  0.244]
[ 5.936  2.77   4.26   1.326]
[ 6.588  2.974  5.552  2.026]


In [125]:
from sklearn.cluster import KMeans

In [166]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)
print(kmeans.cluster_centers_)
print(kmeans.predict(X))


[[ 5.9016129   2.7483871   4.39354839  1.43387097]
 [ 5.006       3.418       1.464       0.244     ]
 [ 6.85        3.07368421  5.74210526  2.07105263]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]
